#!/bin/bash

# Coloring
NOCOLOR='\033[0m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
MAGENTA='\033[0;35m'
GRAY='\033[1;30m'
BOLD_RED='\033[1;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
LIGHT_YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_MAGENTA='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
ORANGE='\033[38;5;208m' # Orange
PINK='\033[38;5;213m' # Pink

# Banner
clear 
____ _   _ _____ _   _   _     ___ _____ _____
 / ___| | | | ____| \ | | | |   |_ _|_   _| ____|
| |   | |_| |  _| |  \| | | |    | |  | | |  _|
| |___|  _  | |___| |\  | | |___ | |  | | | |___
 \____|_| |_|_____|_| \_| |_____|___| |_| |_____|
# Add current date, day, and time without extra text
echo -e "${ORANGE}$(date '+%d %A %Y %I:%M %p')${NOCOLOR}"
echo -e "${CYAN}${BOLD}Telegram:${BOLD_RED}@CHEN_LITE25${NOCOLOR}"
